// Pack tools/out/coupe-parts.json (written by tools/blender/coupe.py) into src/render/models/coupe-hd.js: each part's
// triangles welded into an indexed mesh (same position and normal = one vertex), positions as int16 (1/8000 m),
// normals as int8, indices as uint16, all base64. render/models/index.js decodes them.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const parts = JSON.parse(readFileSync('tools/out/coupe-parts.json', 'utf8')), out = [];
const b64 = a => Buffer.from(a.buffer, a.byteOffset, a.byteLength).toString('base64');
let tris = 0, bytes = 0;
for (const p of parts) {
  const map = new Map(), pos = [], nor = [], idx = [];
  for (let k = 0; k < p.pos.length / 3; k++) {
    const P = [0, 1, 2].map(j => Math.round(p.pos[k * 3 + j] * 8000)), Nn = [0, 1, 2].map(j => Math.round(p.nor[k * 3 + j] * 127)), key = P.join() + '|' + Nn.join();
    let v = map.get(key); if (v === undefined) { v = pos.length / 3; map.set(key, v); pos.push(...P); nor.push(...Nn); }
    idx.push(v);
  }
  if (pos.length / 3 > 65535) throw new Error(`${p.name}: too many vertices`);
  const e = { name: p.name, mat: p.mat, pos: b64(Int16Array.from(pos)), nor: b64(Int8Array.from(nor)), idx: b64(Uint16Array.from(idx)) };
  out.push(e); tris += idx.length / 3; bytes += e.pos.length + e.nor.length + e.idx.length;
}
mkdirSync('src/render/models', { recursive: true });
writeFileSync('src/render/models/coupe-hd.js', `// Generated by tools/blender/export.mjs from the Blender model (tools/blender/coupe.py). Don't edit by hand.\nexport default ${JSON.stringify(out)};\n`);
console.log(`${out.length} parts, ${tris} triangles, ${(bytes / 1024).toFixed(0)} KB`);
