# The Blender lab: build assets headless and pack them for the game.
#   python3 blender/build.py                 every asset
#   python3 blender/build.py car-coupe ...   just these (ids: <prefix>-<name>: car-, scn-, kit-)
#   SAMPLES=64 ...                           preview render quality; NORENDER=1 skips the previews
# Writes src/assets/gen/<id>.js per asset, src/assets/gen/index.js (every packed asset, for the game) and
# src/assets/gen/manifest.json (triangles, size, parts, bounds per asset: tests/assets.test.js checks them), and
# previews to blender/out/<id>-34.png and -top.png.
import sys, os, json, glob, importlib
sys.path.insert(0, os.path.dirname(__file__))
from kit import reset, studio, render, GEN, ROOT
FAMILIES = { 'cars': 'car', 'chassis': 'car', 'scenery': 'scn', 'pieces': 'kit' }   # module -> asset id prefix (chassis: the car families)
def all_designs():
    out = {}
    for fam in FAMILIES:
        mod = importlib.import_module(fam)
        for name, fn in mod.DESIGNS.items(): out[f'{FAMILIES[fam]}-{name}'] = (fam, fn)
    return out
def main(ids):
    designs = all_designs(); ids = ids or list(designs)
    mpath = os.path.join(GEN, 'manifest.json'); man = json.load(open(mpath)) if os.path.exists(mpath) else {}
    for aid in ids:
        if aid not in designs: raise SystemExit(f'unknown asset {aid}; known: {", ".join(designs)}')
        reset(); fam, fn = designs[aid]; st = fn(); studio(); render(aid); man[aid] = st
        print(f'{aid}: {st["hiTris"]} tris near, {st.get("loTris", 0)} far, {st["kb"]} KB')
    for aid in list(man):
        if aid not in designs: del man[aid]
    json.dump(man, open(mpath, 'w'), indent=1, sort_keys=True)
    files = sorted(os.path.basename(f)[:-3] for f in glob.glob(os.path.join(GEN, '*.js')) if not f.endswith('index.js'))
    files = [f for f in files if f in designs]
    ident = lambda f: f.replace('-', '_')
    open(os.path.join(GEN, 'index.js'), 'w').write('// Generated by blender/build.py: every packed Blender asset, by id.\n' + ''.join(f"import {ident(f)} from './{f}.js';\n" for f in files)
        + 'export default { ' + ', '.join(f"'{f}': {ident(f)}" for f in files) + ' };\n')
if __name__ == '__main__': main(sys.argv[1:])
