// Shared mutable game state: anything more than one module writes lives here instead of in loose globals.
export const G = {
  shake: undefined,
  parkVis: undefined,
  bridgeMats: undefined,
  fanChunks: undefined,
  world: undefined,
  glowTex: undefined,
  blobTex: undefined,
  slowmo: undefined,
  attractS: undefined,
  viewH: undefined,
  hudTick: undefined,
  profileTick: undefined,
  standingsKey: undefined,
  lastT: undefined,
  renderAlpha: undefined,
  countdown: undefined,
  lastBeep: undefined,
  state: undefined,
  goTimer: undefined,
  accumulator: undefined,
  resultsTick: undefined,
  calloutTimer: undefined,
  hintTimer: undefined,
};
